##### 1a) Converting to Student Scores to Numpy array>>

In [34]:
import numpy as np

In [51]:
student_scores=[
    [85,92,78,96,88],
    [79,85,91,87,83],
    [92,88,95,91,89],
    [76,82,79,85,81],
    [88,91,87,93,90]
]
scores=np.array(student_scores)
print("Student Scores=",scores)

print("Array Shape=",scores.shape)

print("Array Dimension=",scores.ndim)

Student Scores= [[85 92 78 96 88]
 [79 85 91 87 83]
 [92 88 95 91 89]
 [76 82 79 85 81]
 [88 91 87 93 90]]
Array Shape= (5, 5)
Array Dimension= 2


##### b) Calculating Average score of each student>>

In [8]:
average=scores.mean(axis=1)
print("Average score of each student=",average)

Average score of each student= [87.8 85.  91.  80.6 89.8]


##### c) Finding maximum and minimum of the array>>

In [12]:
maximum=scores.max()
minimum=scores.min()
print(f"Highest score={maximum}\nLowest score={minimum}")

Highest score=96
Lowest score=76


##### d) Test column with the highest average score>>

In [14]:
test_avg=scores.mean(axis=0)
print("Average test scores=",test_avg)
highest_test_avg=np.argmax(test_avg)
print("Highest average test score=",highest_test_avg+1)

Average test scores= [84.  87.6 86.  90.4 86.2]
Highest average test score= 4


##### e) Scores above 90>>

In [26]:
above_90=scores > 90
print("Scores above 90=")
print(above_90)

Scores above 90=
[[False  True False  True False]
 [False False  True False False]
 [ True False  True  True False]
 [False False False False False]
 [False  True False  True False]]


In [53]:
scores[above_90] # this is called masking>>

array([92, 96, 91, 92, 95, 91, 91, 93])

##### f) First 3 students scores on last 2 tests>>>

In [33]:
last2tests=scores[:3,-2:]
print(scores)
print("Last 2 tests scores of the 1st three students=")
print(last2tests)

[[85 92 78 96 88]
 [79 85 91 87 83]
 [92 88 95 91 89]
 [76 82 79 85 81]
 [88 91 87 93 90]]
Last 2 tests scores of the 1st three students=
[[96 88]
 [87 83]
 [91 89]]


#### 2) Analyzing student performance across multiple subjects:

In [68]:
subject_names=["Maths","Science","English","History","Art","PE"]
num_students,num_subjects=50,6
np.random.seed(456)
scores=np.random.randint(60,100,(num_students,num_subjects))
print(scores)

[[87 97 85 88 75 97]
 [88 99 77 71 73 65]
 [94 74 80 94 62 64]
 [68 81 98 76 70 68]
 [95 95 82 95 82 70]
 [81 77 66 91 71 81]
 [86 85 72 80 62 64]
 [75 65 64 81 91 93]
 [70 87 85 64 71 90]
 [88 65 67 83 72 85]
 [75 80 77 86 92 74]
 [72 68 95 68 75 87]
 [75 90 76 99 70 93]
 [96 67 79 97 85 74]
 [80 94 73 71 86 86]
 [84 89 64 99 88 69]
 [82 60 86 60 71 71]
 [84 73 73 97 98 82]
 [63 75 89 98 81 76]
 [98 75 71 81 83 78]
 [62 93 70 85 62 96]
 [76 62 66 79 73 77]
 [98 77 60 86 87 67]
 [92 73 69 72 74 69]
 [75 91 71 94 65 91]
 [64 80 85 65 73 64]
 [83 92 66 79 69 65]
 [89 99 89 88 73 66]
 [69 72 89 71 68 80]
 [78 91 71 90 84 84]
 [96 69 60 61 92 78]
 [91 74 94 63 67 89]
 [73 79 66 64 75 97]
 [74 75 93 74 70 93]
 [62 84 65 98 91 80]
 [70 66 96 87 64 86]
 [66 62 88 98 66 97]
 [76 87 83 81 78 89]
 [99 73 84 81 82 67]
 [78 65 95 77 86 73]
 [73 70 97 85 99 86]
 [94 61 64 93 91 83]
 [91 98 83 87 99 67]
 [91 87 94 86 77 89]
 [69 88 98 74 67 83]
 [60 90 84 90 98 66]
 [66 99 94 89 94 94]
 [76 79 67 94

##### a) Studend who exceled in STEM (Maths + Science average > 90)

In [63]:
stem_avg=scores[:,:2].mean(axis=1)
excel=np.where(stem_avg>90)[0]
print(f'Average scores of students in Maths and Science:{stem_avg}')
print("Students who exceled in Maths and Science (with average above 90)=",excel)

Average scores of students in Maths and Science:[92.  93.5 84.  74.5 95.  79.  85.5 70.  78.5 76.5 77.5 70.  82.5 81.5
 87.  86.5 71.  78.5 69.  86.5 77.5 69.  87.5 82.5 83.  72.  87.5 94.
 70.5 84.5 82.5 82.5 76.  74.5 73.  68.  64.  81.5 86.  71.5 71.5 77.5
 94.5 89.  78.5 75.  82.5 77.5 81.5 74. ]
Students who exceled in Maths and Science (with average above 90)= [ 0  1  4 27 42]


##### b) Identifying struggling students and subjects they struggle with (sunbjects < 70)>>

In [73]:
for i in range(num_students):
    if np.any(scores[i]<70):
        weak_subjects=np.array(subject_names)[scores[i]<70]
        print(f"Student {i+1} struggles with {weak_subjects}")

Student 2 struggles with ['PE']
Student 3 struggles with ['Art' 'PE']
Student 4 struggles with ['Maths' 'PE']
Student 6 struggles with ['English']
Student 7 struggles with ['Art' 'PE']
Student 8 struggles with ['Science' 'English']
Student 9 struggles with ['History']
Student 10 struggles with ['Science' 'English']
Student 12 struggles with ['Science' 'History']
Student 14 struggles with ['Science']
Student 16 struggles with ['English' 'PE']
Student 17 struggles with ['Science' 'History']
Student 19 struggles with ['Maths']
Student 21 struggles with ['Maths' 'Art']
Student 22 struggles with ['Science' 'English']
Student 23 struggles with ['English' 'PE']
Student 24 struggles with ['English' 'PE']
Student 25 struggles with ['Art']
Student 26 struggles with ['Maths' 'History' 'PE']
Student 27 struggles with ['English' 'Art' 'PE']
Student 28 struggles with ['PE']
Student 29 struggles with ['Maths' 'Art']
Student 31 struggles with ['Science' 'English' 'History']
Student 32 struggles with [

##### c) Most challenging subject(lowest average) and best performance in that subject>>

In [92]:
subject_avg=scores.mean(axis=0)
lowest_avg_index=np.argmin(subject_avg)
lowest_avg=subject_avg[lowest_avg_index]
most_challenging_sub=np.array(subject_names)[lowest_avg_index]
best_performance=scores[:,lowest_avg_index].max()
best_students=np.where(scores[:,lowest_avg_index]==best_performance)[0]
print("Subjects Average=",subject_avg)
print(f"Most challenging subject is '{most_challenging_sub}' with an average of '{lowest_avg}'")
print(f"Students {best_students} have the best performance in '{most_challenging_sub}' with score of '{best_performance}'")

Subjects Average= [79.9  79.6  79.68 82.7  78.42 79.48]
Most challenging subject is 'Art' with an average of '78.42'
Students [40 42] have the best performance in 'Art' with score of '99'


#### 3) Analyzing a stock portfolio using Numpy's mathematical functions>>

In [94]:
days=252
stocks=5
stock_names=['AAPL','GOOGL','MSFT','TSLA','AMZN']
initial_price=np.array([150,2800,300,800,3200])
np.random.seed(789)
daily_returns=np.random.normal(0.001,0.02,(days,stocks))

##### a) Basic Analysis>>

##### i) Cumulative Returns for each stock>>>

In [95]:
daily_returns

array([[-0.02116223, -0.01351437,  0.01145609,  0.02568884,  0.00293792],
       [-0.01875844,  0.00234466, -0.01085184, -0.01763542,  0.02210726],
       [ 0.01710345,  0.02771369, -0.00750256, -0.00537071, -0.01628741],
       ...,
       [-0.00594361, -0.00918097,  0.0290994 , -0.02367441, -0.01087742],
       [-0.0119153 , -0.01296554, -0.00542998,  0.01199449,  0.00495045],
       [ 0.00849359,  0.02542862,  0.00152298,  0.00522356,  0.01760987]])

In [99]:
stock_cumulative_returns=np.cumprod(1+daily_returns,axis=0)-1
final_stock_cum_returns=stock_cumulative_returns[-1]
print("Cumulative Returns=")
for i in range(stocks):
    print(stock_names[i],"===", round(final_stock_cum_returns[i],3))

Cumulative Returns=
AAPL === 0.019
GOOGL === 0.383
MSFT === -0.076
TSLA === 1.579
AMZN === 0.171


##### ii) Annualized volatility (standard deviation * sqrt(252))>>>

In [100]:
volatility=np.std(daily_returns,axis=0)*np.sqrt(252)
print("Annualized volatility:")
for i in range(stocks):
    print(stock_names[i],">>>", round(volatility[i],3))

Annualized volatility:
AAPL >>> 0.318
GOOGL >>> 0.341
MSFT >>> 0.304
TSLA >>> 0.324
AMZN >>> 0.298


##### iii) Best and worst performing stock>>>

In [103]:
best_stock_index=np.argmax(final_stock_cum_returns)
best_stock=(final_stock_cum_returns)[best_stock_index]
worst_stock_index=np.argmin(final_stock_cum_returns)
worst_stock=(final_stock_cum_returns)[worst_stock_index]
print("Best performing stock:")
print(np.array(stock_names)[best_stock_index], "with", round(best_stock,3), "Stocks")
print("Worst performing stock:")
print(np.array(stock_names)[worst_stock_index], "with", round(worst_stock,3),"Stocks")

Best performing stock:
TSLA with 1.579 Stocks
Worst performing stock:
MSFT with -0.076 Stocks


##### b) Risk Metrics>>>

##### i) Calculating sharpe ratio (return/volatility) for each stock>>>

In [105]:
sharpe_ratio=final_stock_cum_returns/volatility
print ("Sharpe Ratio:")
for i in range(stocks):
    print(stock_names[i], ">>>", round(sharpe_ratio[i],3))

Sharpe Ratio:
AAPL >>> 0.059
GOOGL >>> 1.123
MSFT >>> -0.251
TSLA >>> 4.871
AMZN >>> 0.573


##### ii) Maximum drawdown (largest_peak_to_trough_decline)>>>

In [106]:
prices=initial_price*(1+stock_cumulative_returns)
max_drawdown=[]
for i in range(stocks):
    peak=prices[:,i].max()
    trough=prices[:,i].min()
    drawdown=(trough-peak)/peak
    max_drawdown.append(drawdown)
print("Maximum Drawdown:")
for i in range (stocks):
    print(stock_names[i], ">>>", round(max_drawdown[i],3))

Maximum Drawdown:
AAPL >>> -0.227
GOOGL >>> -0.55
MSFT >>> -0.439
TSLA >>> -0.623
AMZN >>> -0.333


##### iii) Correlation matrix between stocks>>>

In [107]:
correlaion_matrix=np.corrcoef(daily_returns.T)
print("Correlation Matrix:")
print(correlaion_matrix)

Correlation Matrix:
[[ 1.          0.01558858  0.0016994  -0.10262945  0.08717904]
 [ 0.01558858  1.         -0.15014226  0.08813674  0.03835865]
 [ 0.0016994  -0.15014226  1.          0.01366414 -0.02847043]
 [-0.10262945  0.08813674  0.01366414  1.         -0.11192288]
 [ 0.08717904  0.03835865 -0.02847043 -0.11192288  1.        ]]
